# new strong model with proper reasoning
- llm:
    provider: OpenRouter
    model: google/gemini-3-flash-preview
    kwargs:
      temperature: 1
      reasoning:
        effort: medium
  type: CoTAgent

# new strong model without reasoning
- llm:
    provider: OpenRouter
    model: google/gemini-3-flash-preview
    kwargs:
      temperature: 1
      reasoning:
        effort: none
  type: IOAgent

# new strong model
- llm:
    provider: OpenRouter
    model: openai/gpt-5.2
    kwargs:
      temperature: 1
      reasoning:
        effort: low
  type: CoTAgent

# Old strong model
- llm:
    provider: OpenRouter
    model: openai/gpt-4o-2024-05-13
    kwargs:
      temperature: 1
  type: CoTAgent

# "Safe" strong model
- llm:
    provider: OpenRouter
    model: anthropic/claude-sonnet-4.5
    kwargs:
      temperature: 1
      reasoning:
        effort: low
  type: CoTAgent

# Open-weight flagship small model
- llm:
    provider: OpenRouter
    model: qwen/qwen3-30b-a3b-instruct-2507
    kwargs:
      temperature: 1
  type: CoTAgent

