# Prisoners' Dilemma with Repetition mechanism using OpenRouter API models

game:
  type: PublicGoods
  kwargs:
    multiplier: 1.5
    num_players: 4

evolution:
  initial_population: uniform
  steps: 3

mechanism:
  type: Reputation
  kwargs:
    num_rounds: 10
    discount: 0.95
    lookup_depth: 3
    max_recursion_depth: 2
    include_prior_distributions: false
    

  # type: Repetition
  # kwargs:
  #   num_rounds: 10
  #   discount: 0.95
  #   lookup_depth: 3
  #   include_prior_distributions: true

agents:

  - llm:
      provider: TestInstance
      model: test-1
    type: CoTAgent

  - llm:
      provider: TestInstance
      model: test-2
    type: CoTAgent

  - llm:
      provider: TestInstance
      model: test-3
    type: CoTAgent
  

  # - llm:
  #     provider: OpenRouter
  #     model: google/gemini-2.5-flash-lite-preview-09-2025
  #     kwargs:
  #       temperature: 0
  #   type: CoTAgent

  # - llm:
  #     provider: OpenRouter
  #     model: openai/gpt-4o-2024-05-13
  #     kwargs:
  #       temperature: 0
  #   type: CoTAgent

  # - llm:
  #     provider: OpenRouter
  #     model: qwen/qwen3-next-80b-a3b-instruct
  #     kwargs:
  #       temperature: 0
  #   type: CoTAgent

  # - llm:
  #     provider: OpenRouter
  #     model: openai/gpt-5-nano
  #     kwargs:
  #       temperature: 0
  #   type: CoTAgent
