game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [1, 1]
      CD: [1, 1]
      DC: [1, 1]
      DD: [1, 1]

evolution:
  initial_population: uniform
  steps: 2

mechanism:
  type: Repetition
  kwargs:
    num_rounds: 3
    discount: 1


concurrency:
  max_workers: 2

agents:
  # - llm:
  #     provider: HFInstance
  #     model: Meta-Llama-3.1-8B-Instruct
  #     kwargs:
  #       max_new_tokens: 2048
  #   type: CoTAgent

  - llm:
      provider: OpenRouter
      model: openai/gpt-oss-20b:free
      kwargs:
        temperature: 0
    type: CoTAgent

  - llm:
      provider: OpenRouter
      model: deepseek/deepseek-chat-v3.1:free
      kwargs:
        temperature: 0
    type: CoTAgent